=== yxxyun/ScoopMaster/bucket/schema.json
{
  "$id": "http://scoop.sh/draft/schema#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "hashPattern": {
      "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
      "type": "string"
    },
    "jsonPathPattern": {
      "pattern": "^\\$[.\\[].*$",
      "type": "string"
    },
    "hash": {
      "anyOf": [
        {
          "$ref": "#/definitions/hashPattern"
        },
        {
          "items": {
            "$ref": "#/definitions/hashPattern"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        }
      ]
    },
    "hashExtraction": {
      "additionalProperties": false,
      "properties": {
        "find": {
          "format": "regex",
          "type": "string",
          "description": "Same as 'regex'"
        },
        "regex": {
          "format": "regex",
          "type": "string"
        },
        "jp": {
          "$ref": "#/definitions/jsonPathPattern",
          "description": "Same as 'jsonpath'"
        },
        "jsonpath": {
          "$ref": "#/definitions/jsonPathPattern"
        },
        "xpath": {
          "type": "string"
        },
        "mode": {
          "enum": [
            "download",
            "extract",
            "json",
            "xpath",
            "rdf",
            "metalink",
            "fosshub",
            "sourceforge"
          ]
        },
        "type": {
          "enum": [
            "md5",
            "sha1",
            "sha256",
            "sha512"
          ],
          "description": "Deprecated, hash type is determined automatically"
        },
        "url": {
          "anyOf": [
            {
              "format": "uri",
              "type": "string"
            },
            {
              "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
              "type": "string"
            },
            {
              "pattern": "^.*(\\$url|\\$baseurl).*$",
              "type": "string"
            }
          ]
        }
      },
      "type": "object"
    },
    "hashExtractionOrArrayOfHashExtractions": {
      "anyOf": [
        {
          "$ref": "#/definitions/hashExtraction"
        },
        {
          "items": {
            "$ref": "#/definitions/hashExtraction"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": false
        }
      ]
    },
    "architecture": {
      "additionalProperties": false,
      "properties": {
        "bin": {
          "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
          "$ref": "#/definitions/checkver"
        },
        "env_add_path": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
          "type": "object"
        },
        "extract_dir": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "hash": {
          "$ref": "#/definitions/hash"
        },
        "installer": {
          "$ref": "#/definitions/installer"
        },
        "post_install": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "post_uninstall": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_uninstall": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "shortcuts": {
          "$ref": "#/definitions/shortcutsArray"
        },
        "uninstaller": {
          "$ref": "#/definitions/uninstaller"
        },
        "url": {
          "$ref": "#/definitions/uriOrArrayOfUris"
        }
      },
      "type": "object"
    },
    "arrayOfArrayOfStrings": {
      "items": {
        "items": {
          "type": "string"
        },
        "minItems": 1,
        "type": "array"
      },
      "minItems": 1,
      "type": "array"
    },
    "shortcutsArray": {
      "items": {
        "items": {
          "type": "string"
        },
        "minItems": 2,
        "maxItems": 4,
        "type": "array"
      },
      "minItems": 1,
      "type": "array"
    },
    "autoupdateArch": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bin": {
          "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "env_add_path": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
          "type": "object"
        },
        "extract_dir": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "hash": {
          "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
        },
        "installer": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "file": {
              "type": "string"
            }
          }
        },
        "shortcuts": {
          "$ref": "#/definitions/shortcutsArray"
        },
        "url": {
          "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
        }
      }
    },
    "autoupdate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "architecture": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "32bit": {
              "$ref": "#/definitions/autoupdateArch"
            },
            "64bit": {
              "$ref": "#/definitions/autoupdateArch"
            },
            "arm64": {
              "$ref": "#/definitions/autoupdateArch"
            }
          }
        },
        "bin": {
          "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "env_add_path": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
          "type": "object"
        },
        "extract_dir": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "hash": {
          "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
        },
        "installer": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "file": {
              "type": "string"
            }
          }
        },
        "license": {
          "$ref": "#/definitions/license"
        },
        "notes": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
          "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "persist_external": {
          "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "psmodule": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "shortcuts": {
          "$ref": "#/definitions/shortcutsArray"
        },
        "url": {
          "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
        }
      }
    },
    "checkver": {
      "anyOf": [
        {
          "format": "regex",
          "type": "string"
        },
        {
          "additionalProperties": false,
          "properties": {
            "github": {
              "format": "uri",
              "type": "string"
            },
            "re": {
              "format": "regex",
              "type": "string",
              "description": "Same as 'regex'"
            },
            "regex": {
              "format": "regex",
              "type": "string"
            },
            "url": {
              "format": "uri",
              "type": "string"
            },
            "jp": {
              "$ref": "#/definitions/jsonPathPattern",
              "description": "Same as 'jsonpath'"
            },
            "jsonpath": {
              "$ref": "#/definitions/jsonPathPattern"
            },
            "xpath": {
              "type": "string"
            },
            "reverse": {
              "description": "Reverse the order of regex matches",
              "type": "boolean"
            },
            "replace": {
              "description": "Allows rearrange the regexp matches",
              "type": "string"
            },
            "useragent": {
              "type": "string"
            },
            "script": {
              "$ref": "#/definitions/stringOrArrayOfStrings",
              "description": "Custom PowerShell script to retrieve application version using more complex approach."
            },
            "sourceforge": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "additionalProperties": false,
                  "properties": {
                    "project": {
                      "type": "string"
                    },
                    "path": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              ]
            }
          },
          "type": "object"
        }
      ]
    },
    "installer": {
      "additionalProperties": false,
      "properties": {
        "_comment": {
          "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
          "type": "string"
        },
        "args": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "file": {
          "type": "string"
        },
        "script": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "keep": {
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "stringOrArrayOfStrings": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "type": "array"
        }
      ]
    },
    "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "minItems": 1,
          "type": "array"
        }
      ]
    },
    "uninstaller": {
      "properties": {
        "args": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "file": {
          "type": "string"
        },
        "script": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        }
      },
      "oneOf": [
        {
          "required": [
            "file"
          ]
        },
        {
          "required": [
            "script"
          ]
        }
      ],
      "type": "object"
    },
    "uriOrArrayOfUris": {
      "anyOf": [
        {
          "format": "uri",
          "not": {
            "pattern": "(\\$)"
          },
          "type": "string"
        },
        {
          "items": {
            "format": "uri",
            "not": {
              "pattern": "(\\$)"
            },
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        }
      ]
    },
    "autoupdateUriOrArrayOfAutoupdateUris": {
      "anyOf": [
        {
          "format": "uri",
          "type": "string"
        },
        {
          "items": {
            "format": "uri",
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        }
      ]
    },
    "licenseIdentifiers": {
      "type": "string",
      "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
      "examples": [
        "Apache-2.0",
        "BSD-3-Clause",
        "Freeware",
        "GPL-2.0-only",
        "GPL-2.0-or-later",
        "GPL-3.0-only",
        "GPL-3.0-or-later",
        "ISC",
        "LGPL-2.0-only",
        "LGPL-2.0-or-later",
        "LGPL-2.1-only",
        "LGPL-2.1-or-later",
        "LGPL-3.0-only",
        "LGPL-3.0-or-later",
        "MIT",
        "MS-PL",
        "Proprietary",
        "Public Domain",
        "Shareware",
        "Unlicense"
      ]
    },
    "license": {
      "anyOf": [
        {
          "$ref": "#/definitions/licenseIdentifiers"
        },
        {
          "additionalProperties": false,
          "properties": {
            "url": {
              "format": "uri",
              "type": "string"
            },
            "identifier": {
              "$ref": "#/definitions/licenseIdentifiers"
            }
          },
          "required": [
            "identifier"
          ],
          "type": "object"
        }
      ]
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "_comment": {
      "description": "Deprecated. Use ## instead.",
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "##": {
      "description": "A comment.",
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "architecture": {
      "additionalProperties": false,
      "properties": {
        "32bit": {
          "$ref": "#/definitions/architecture"
        },
        "64bit": {
          "$ref": "#/definitions/architecture"
        },
        "arm64": {
          "$ref": "#/definitions/architecture"
        }
      },
      "type": "object"
    },
    "autoupdate": {
      "$ref": "#/definitions/autoupdate"
    },
    "bin": {
      "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
    },
    "persist": {
      "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
    },
    "persist_external": {
      "description": "Persist folders/files outside application install directory using symlinks.",
      "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
    },
    "checkver": {
      "$ref": "#/definitions/checkver"
    },
    "cookie": {
      "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
      "type": "object"
    },
    "depends": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "description": {
      "type": "string"
    },
    "env_add_path": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "env_set": {
      "type": "object"
    },
    "extract_dir": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "extract_to": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "hash": {
      "$ref": "#/definitions/hash"
    },
    "homepage": {
      "format": "uri",
      "type": "string"
    },
    "innosetup": {
      "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Main/search?l=JSON&q=innosetup",
      "type": "boolean"
    },
    "installer": {
      "$ref": "#/definitions/installer"
    },
    "license": {
      "$ref": "#/definitions/license"
    },
    "notes": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "post_install": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "post_uninstall": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "pre_install": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "pre_uninstall": {
      "$ref": "#/definitions/stringOrArrayOfStrings"
    },
    "psmodule": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "shortcuts": {
      "$ref": "#/definitions/shortcutsArray"
    },
    "suggest": {
      "additionalProperties": false,
      "patternProperties": {
        "^(.*)$": {
          "$ref": "#/definitions/stringOrArrayOfStrings"
        }
      },
      "type": "object"
    },
    "uninstaller": {
      "$ref": "#/definitions/uninstaller"
    },
    "url": {
      "$ref": "#/definitions/uriOrArrayOfUris"
    },
    "version": {
      "pattern": "^[\\w\\.\\-+_]+$",
      "type": "string"
    }
  },
  "if": {
    "properties": {
      "architecture": {
        "properties": {
          "64bit": {
            "properties": {
              "url": false
            }
          },
          "32bit": {
            "properties": {
              "url": false
            }
          },
          "arm64": {
            "properties": {
              "url": false
            }
          }
        }
      }
    }
  },
  "then": {
    "required": [
      "url"
    ]
  },
  "required": [
    "version",
    "homepage",
    "license"
  ],
  "title": "scoop app manifest schema",
  "type": "object"
}

=== yxxyun/ScoopMaster/bucket/Dexpot.json
{
    "homepage": "https://dexpot.de/",
    "version": "1.6.14.2439",
    "license": "free for private use",
    "url": "https://dexpot.de/download/dexpot_1614_portable_r2439.zip",
    "hash": "f3f0603d1fdf6719f00cfa0e3aca17a657f98b2b5649b73b6c4c66ceaac98b49",
    "bin": "Dexpot.exe",
    "shortcuts": [
        [
            "Dexpot.exe",
            "Dexpot"
        ]
    ],
    "checkver": {
        "url": "https://dexpot.de/?id=changelog",
        "regex": "Dexpot ([\\d.]+) Build (\\d+)",
        "replace": "${1}.${2}"
    },
    "autoupdate": {
        "url": "https://dexpot.de/download/dexpot_$majorVersion$minorVersion$patchVersion_portable_r$buildVersion.zip"
    }
}

=== yxxyun/ScoopMaster/bucket/omniget-openselena.json
{
  "version": "0.12.0",
  "description": "Official repository of OmniGet - Open-source download manager for courses (Udemy/Hotmart), YouTube, music & 1,800+ sites. Built with Tauri 2.0, Rust & Svelte.",
  "homepage": "https://omniget.nav.bd/",
  "license": {
    "identifier": "GPL-3.0 license",
    "url": "https://github.com/OpenSelena/omniget#GPL-3.0-1-ov-file"
  },
  "architecture": {
    "64bit": {
      "url": "https://github.com/OpenSelena/omniget/releases/download/v0.12.0/omniget_0.12.0_x64-setup.exe",
      "hash": "3cc2c1f6bd68175108a25d6f0b6de6a75d1e572a1fef9a6631e2ca344ffb6869",
      "pre_install": "Remove-Item \"$dir\\`$*\", \"$dir\\uninst*\" -Force -Recurse"
    }
  },
  "installer": {
    "script": [
      "# handle runtime cache",
      "Import-Module $(Join-Path $(Find-BucketDirectory -Root -Name apps) scripts/AppsUtils.psm1)",
      "Mount-ExternalRuntimeData -Source \"$persist_dir\\appdata\" -Target \"$env:LOCALAPPDATA\\com.openselena.omniget\"",
      "Mount-ExternalRuntimeData -Source \"$persist_dir\\userdata\" -Target \"$env:APPDATA\\com.openselena.omniget\"",
      "Remove-Module -Name AppsUtils"
    ]
  },
  "uninstaller": {
    "script": [
      "Import-Module $(Join-Path $(Find-BucketDirectory -Root -Name apps) scripts/AppsUtils.psm1)",
      "Dismount-ExternalRuntimeData -Target \"$env:LOCALAPPDATA\\com.openselena.omniget\"",
      "Dismount-ExternalRuntimeData -Target \"$env:APPDATA\\com.openselena.omniget\"",
      "Remove-Module -Name AppsUtils"
    ]
  },
  "bin": "omniget.exe",
  "shortcuts": [
    [
      "omniget.exe",
      "omniget"
    ]
  ],
  "checkver": {
    "github": "https://api.github.com/repos/OpenSelena/omniget/releases",
    "jp": "$[0].tag_name",
    "regex": "v([\\d.]+)"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/OpenSelena/omniget/releases/download/v$version/omniget_$version_x64-setup.exe"
      }
    }
  }
}

=== yxxyun/ScoopMaster/bucket/php84.json
{
  "version": "8.4.27",
  "description": "PHP, a popular general-purpose scripting language that is especially suited to web development. (version 8.4)",
  "homepage": "https://www.php.net",
  "license": "PHP-3.01",
  "suggest": {
    "vcredist": "extras/vcredist2022"
  },
  "architecture": {
    "64bit": {
      "url": "https://downloads.php.net/~windows/releases/archives/php-8.4.27-Win32-vs17-x64.zip",
      "hash": "7902fe891ff4b035d431fd429a2ec1df193ba1f6fedba425d861790465c64e6b"
    },
    "32bit": {
      "url": "https://downloads.php.net/~windows/releases/archives/php-8.4.27-Win32-vs17-x86.zip",
      "hash": "b1f02421a1f92e65930cdf6d5819138cd4ceb120740ef05968387fe72a3c6bda"
    }
  },
  "pre_install": [
    "# Create directory for custom PHP configuration",
    "if (!(Test-Path \"$dir\\cli\\conf.d\")) {",
    "    (New-Item -Type directory \"$dir\\cli\\conf.d\") | Out-Null",
    "}"
  ],
  "post_install": [
    "# Enable extensions to be found in installation-relative folder (the default is to search C:/php)",
    "(Get-Content \"$dir\\cli\\php.ini\") | % { $_ -replace ';\\s?(extension_dir = \"ext\")', '$1' } | Set-Content \"$dir\\cli\\php.ini\""
  ],
  "bin": [
    "php.exe",
    "php-cgi.exe",
    "phpdbg.exe"
  ],
  "env_set": {
    "PHP_INI_SCAN_DIR": "$dir\\cli;$dir\\cli\\conf.d;"
  },
  "persist": [
    "cli",
    [
      "php.ini-production",
      "cli\\php.ini"
    ]
  ],
  "checkver": {
    "url": "https://www.php.net/releases/branches.php",
    "jsonpath": "$.[?(@.branch == '8.4')].latest"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://downloads.php.net/~windows/releases/archives/php-$version-Win32-vs17-x64.zip"
      },
      "32bit": {
        "url": "https://downloads.php.net/~windows/releases/archives/php-$version-Win32-vs17-x86.zip"
      }
    },
    "hash": {
      "url": "https://downloads.php.net/~windows/releases/sha256sum.txt"
    }
  }
}

=== yxxyun/ScoopMaster/bucket/fab.json
{
    "version": "1.9",
    "description": "Firewall App Blocker (Fab) 易于使用的Windows防火墙工具 ",
    "homepage": "https://www.sordum.org/downloads/?firewall-app-blocker",
    "license": "Freeware",
    "url": "https://www.sordum.org/files/download/firewall-app-blocker/fab.zip",
    "hash": "a3ba4fd717e892eea3ca627ffe84056eb392f3541aa85e43a57b83436e752803",
    "extract_dir": "fab",
    "architecture": {
        "32bit": {
            "shortcuts": [
                [
                    "Fab.exe",
                    "Firewall App Blocker"
                ]
            ]
        },
        "64bit": {
            "shortcuts": [
                [
                    "Fab_x64.exe",
                    "Firewall App Blocker"
                ]
            ]
        }
    },
    "persist": "Fab.ini",
    "checkver": {
        "url": "https://www.sordum.org/downloads/?firewall-app-blocker",
        "regex": "<title>Download Firewall App Blocker v([\\d.]+)</title>"
    },
    "autoupdate": {
        "url": "https://www.sordum.org/files/download/firewall-app-blocker/fab.zip"
    }
}

=== yxxyun/ScoopMaster/bucket/llvm-mingw_chawyehsu.json
{
  "homepage": "https://github.com/mstorsjo/llvm-mingw",
  "description": "An LLVM/Clang/LLD based mingw-w64 GNU toolchain",
  "version": "22.1.6-20260519",
  "license": "ISC",
  "architecture": {
    "64bit": {
      "url": "https://github.com/mstorsjo/llvm-mingw/releases/download/20260519/llvm-mingw-20260519-ucrt-x86_64.zip",
      "hash": "72dbd6e64614e3b3401998992d1bd9c8ace29e74611d71c80309ea71c3fb26f9",
      "extract_dir": "llvm-mingw-20260519-ucrt-x86_64"
    },
    "32bit": {
      "url": "https://github.com/mstorsjo/llvm-mingw/releases/download/20260519/llvm-mingw-20260519-ucrt-i686.zip",
      "hash": "19a019665bda2107ba298a94dab2749523d3a40bd8f304ad6a0c18d55b4875db",
      "extract_dir": "llvm-mingw-20260519-ucrt-i686"
    },
    "arm64": {
      "url": "https://github.com/mstorsjo/llvm-mingw/releases/download/20260519/llvm-mingw-20260519-ucrt-aarch64.zip",
      "hash": "7bb5e3c9964dc29555cababb55e69eea02a51e98e1240eb9513e6540c7bae0ea",
      "extract_dir": "llvm-mingw-20260519-ucrt-aarch64"
    }
  },
  "env_add_path": "bin",
  "checkver": {
    "regex": "llvm-mingw\\s+(?<date>\\d+)\\swith\\s+LLVM\\s+(?<llvmversion>[\\d.]+)",
    "replace": "${llvmversion}-${date}"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/mstorsjo/llvm-mingw/releases/download/$matchDate/llvm-mingw-$matchDate-ucrt-x86_64.zip",
        "extract_dir": "llvm-mingw-$matchDate-ucrt-x86_64"
      },
      "32bit": {
        "url": "https://github.com/mstorsjo/llvm-mingw/releases/download/$matchDate/llvm-mingw-$matchDate-ucrt-i686.zip",
        "extract_dir": "llvm-mingw-$matchDate-ucrt-i686"
      },
      "arm64": {
        "url": "https://github.com/mstorsjo/llvm-mingw/releases/download/$matchDate/llvm-mingw-$matchDate-ucrt-aarch64.zip",
        "extract_dir": "llvm-mingw-$matchDate-ucrt-aarch64"
      }
    }
  }
}

=== yxxyun/ScoopMaster/bucket/warmup-s3-archives.json
{
    "version": "1.3.0",
    "description": "A warmup program that facilitates restoring archived objects from Amazon S3 Glacier storage classes:",
    "homepage": "https://gitlab.com/philipmw/warmup-s3-archives",
    "license": "ISC",
    "architecture": {
        "64bit": {
            "url": "https://gitlab.com/philipmw/warmup-s3-archives/-/releases/v1.3.0/downloads/warmup-s3-archives-v1.3.0-windows-x86_64.exe#/warmup-s3-archives.exe",
            "hash": "fa19380e98ef487d5cac1fa0e8a0c24b8029496757171f2d798efcd2d3434728"
        }
    },
    "bin": "warmup-s3-archives.exe",
    "checkver": {
        "url": "https://gitlab.com/api/v4/projects/philipmw%2Fwarmup-s3-archives/releases/?per_page=1",
        "jsonpath": "$.[0].tag_name",
        "regex": "v([\\d.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://gitlab.com/philipmw/warmup-s3-archives/-/releases/v$version/downloads/warmup-s3-archives-v$version-windows-x86_64.exe#/warmup-s3-archives.exe"
            }
        }
    }
}

=== yxxyun/ScoopMaster/bucket/glazewm-tray.json
{
  "version": "0.2.0-beta1",
  "description": "A system tray app that shows GlazeWM current workspace, pause state, and more",
  "homepage": "https://github.com/babysnakes/GlazeWM-Tray",
  "architecture": {
    "64bit": {
      "url": "https://github.com/babysnakes/GlazeWM-Tray/releases/download/v0.2.0-beta1/GlazeWM-Tray_0.2.0-beta1_win-x64.zip",
      "hash": "775667078D087B61642E598D111096A383E712DDD8246B036D434C939EA57379"
    },
    "arm64": {
      "url": "https://github.com/babysnakes/GlazeWM-Tray/releases/download/v0.2.0-beta1/GlazeWM-Tray_0.2.0-beta1_win-arm64.zip",
      "hash": "616CEF99655EE8BB0C0C8C8B41FF26AB20F9EA2F4277A1F3DCDB29C00788B91B"
    }
  },
  "license":"MIT",
  "shortcuts": [
    [
        "GlazeWM-Tray.exe",
        "GlazeWM-Tray"
    ]
  ]
}

=== yxxyun/ScoopMaster/bucket/wifiinfoview.json
{
    "version": "3.00",
    "homepage": "https://www.nirsoft.net/utils/wifi_information_view.html",
    "bin": "WifiInfoView.exe",
    "shortcuts": [
        [
            "WifiInfoView.exe",
            "NirSoft\\WifiInfoView"
        ]
    ],
    "pre_install": [
        "New-Item -Path $dir\\wifiinfoview.cfg | Out-Null",
        "New-Item -Path $dir\\wifiinfoview_lng.ini | Out-Null"
    ],
    "persist": [
        "wifiinfoview_lng.ini",
        "wifiinfoview.cfg"
    ],
    "architecture": {
        "64bit": {
            "url": "https://www.nirsoft.net/utils/wifiinfoview-x64.zip",
            "hash": "9264a6ef47b882fa67b9431f6410c62be091524c39877a09cf6744dea8d8a988"
        },
        "32bit": {
            "url": "https://www.nirsoft.net/utils/wifiinfoview.zip",
            "hash": "7281c7a7f90a796549e3cffa41a9beb0faf3feec549f914e5dd3c17cdbc7cfca"
        }
    },
    "description": "Displays extensive information about wireless networks in your area.",
    "license": "Freeware",
    "notes": "If this application is useful to you, please consider donating to NirSoft - https://www.nirsoft.net/donate.html",
    "checkver": {
        "url": "https://www.nirsoft.net/pad/wifiinfoview.xml",
        "xpath": "/XML_DIZ_INFO/Program_Info/Program_Version"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://www.nirsoft.net/utils/wifiinfoview-x64.zip"
            },
            "32bit": {
                "url": "https://www.nirsoft.net/utils/wifiinfoview.zip"
            }
        }
    }
}
